[Fixed] NoMethodError: undefined method `close' for #<FakeWeb::StubSocket:0x00007fbd671e9728>
```
  1) Error:
Connpass::.event_search#test_0001_return converted API results:
NoMethodError: undefined method `close' for #<FakeWeb::StubSocket:0x00007fbd671e9728>
Did you mean?  closed?
               clone
    /Users/sue445/.rbenv/versions/3.0.3/lib/ruby/3.0.0/net/http.rb:1071:in `do_finish'
    /Users/sue445/.rbenv/versions/3.0.3/lib/ruby/3.0.0/net/http.rb:962:in `start'
    /Users/sue445/.rbenv/versions/3.0.3/lib/ruby/3.0.0/open-uri.rb:323:in `open_http'
    /Users/sue445/.rbenv/versions/3.0.3/lib/ruby/3.0.0/open-uri.rb:741:in `buffer_open'
    /Users/sue445/.rbenv/versions/3.0.3/lib/ruby/3.0.0/open-uri.rb:212:in `block in open_loop'
    /Users/sue445/.rbenv/versions/3.0.3/lib/ruby/3.0.0/open-uri.rb:210:in `catch'
    /Users/sue445/.rbenv/versions/3.0.3/lib/ruby/3.0.0/open-uri.rb:210:in `open_loop'
    /Users/sue445/.rbenv/versions/3.0.3/lib/ruby/3.0.0/open-uri.rb:151:in `open_uri'
    /Users/sue445/.rbenv/versions/3.0.3/lib/ruby/3.0.0/open-uri.rb:721:in `open'
    /Users/sue445/.rbenv/versions/3.0.3/lib/ruby/3.0.0/open-uri.rb:29:in `open'
    /Users/sue445/workspace/github.com/deeeki/connpass/lib/connpass/connection.rb:11:in `get'
    /Users/sue445/workspace/github.com/deeeki/connpass/lib/connpass/event.rb:4:in `event_search'
    /Users/sue445/workspace/github.com/deeeki/connpass/spec/connpass_spec.rb:17:in `block (3 levels) in <top (required)>'
```